name: Build dnscat2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ruby-dev gcc make
        gem install bundler --user-install
        export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
        echo 'export PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"' >> $GITHUB_ENV

    - name: Setup Server
      run: |
        echo "Current PATH: $PATH"
        export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
        echo "Updated PATH: $PATH"
        cd server
        $(ruby -e 'puts Gem.user_dir')/bin/bundle install --path vendor/bundle

    - name: Build Client
      run: |
        cd client
        make

    - name: Upload Linux Client Binary
      uses: actions/upload-artifact@v4
      with:
        name: dnscat2-client-linux
        path: client/dnscat

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        # Скачать MinGW
        Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev0.7z" -OutFile "C:\\Temp\\mingw.7z"
        
        # Распаковать MinGW
        Expand-Archive -Path "C:\\Temp\\mingw.7z" -DestinationPath "C:\\MinGW"
        
        # Обновить PATH
        $env:PATH = "C:\\MinGW\\bin;" + $env:PATH
        [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::Process)
        Write-Host "PATH updated: $env:PATH"
    
        # Проверка установленных инструментов
        if (-Not (Get-Command "gcc" -ErrorAction SilentlyContinue)) {
            Write-Error "GCC is not available in PATH!"
            exit 1
        }
        if (-Not (Get-Command "make" -ErrorAction SilentlyContinue)) {
            Write-Error "Make is not available in PATH!"
            exit 1
        }
        Write-Host "GCC and Make are available."

    - name: Build Client
      run: |
        cd client
        make -f Makefile.win

    - name: Upload Windows Client Binary
      uses: actions/upload-artifact@v4
      with:
        name: dnscat2-client-windows
        path: client/dnscat2-client.exe
