name: Build dnscat2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ruby-dev gcc make
        gem install bundler --user-install
        export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
        echo 'export PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"' >> $GITHUB_ENV

    - name: Setup Server
      run: |
        echo "Current PATH: $PATH"
        export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
        echo "Updated PATH: $PATH"
        cd server
        $(ruby -e 'puts Gem.user_dir')/bin/bundle install --path vendor/bundle

    - name: Build Client
      run: |
        cd client
        make

    - name: Upload Linux Client Binary
      uses: actions/upload-artifact@v4
      with:
        name: dnscat2-client-linux
        path: client/dnscat

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        choco install make mingw -y
        $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        if (-Not (Test-Path $mingwPath)) {
            Write-Error "MinGW path does not exist: $mingwPath"
            exit 1
        }
        $env:PATH = "$mingwPath;$env:PATH"
        Write-Host "PATH updated: $env:PATH"

    - name: Build Client
      run: |
        cd client
        make -f Makefile.win

    - name: Upload Windows Client Binary
      uses: actions/upload-artifact@v4
      with:
        name: dnscat2-client-windows
        path: client/dnscat2-client.exe
