name: Build dnscat2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ruby-dev gcc make
        gem install bundler --user-install
        export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
        echo 'export PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"' >> $GITHUB_ENV

    - name: Setup Server
      run: |
        cd server
        $(ruby -e 'puts Gem.user_dir')/bin/bundle install --path vendor/bundle

    - name: Build Client
      run: |
        cd client
        make

    - name: Debug Client Directory
      run: |
        echo "Contents of client directory:"
        ls -l client
        echo "Recursive contents of client directory:"
        ls -R client

    - name: Upload Client Binary
      uses: actions/upload-artifact@v4
      with:
        name: dnscat2-client
        path: client/dnscat
